import {
  TReunion,
  TMembre,
  TTransaction,
  TActivite,
  TNotification,
} from './types';

export const reunions: TReunion[] = [
  {
    id: 'r1',
    idInscription: '001-23-4567',
    idCreateur: 'm1',
    nomReunion: 'Investissement Futur',
    description1: 'Réunion d’investissement collectif',
    description2: 'Stratégies et opportunités d’investissement',
    type: 'Investissement',
    dateCreation: '2023-01-15',
    epargne: false,
    aide: false,
    groupeWhatsapp: 'https://chat.whatsapp.com/invitationLink1',
    idRejetes: [],
  },
  {
    id: 'r2',
    idInscription: '002-34-5678',
    idCreateur: 'm2',
    nomReunion: 'Solidarité et Épargne',
    description1: 'Réunion tournante de solidarité',
    description2: 'Épargne collective pour projets communs',
    type: 'Tournante',
    dateCreation: '2022-11-25',
    epargne: true,
    aide: true,
    groupeWhatsapp: 'https://chat.whatsapp.com/invitationLink2',
    idRejetes: [],
  },
  {
    id: 'r3',
    idInscription: '003-50-6588',
    idCreateur: 'm3',
    nomReunion: 'Opportunités Financières',
    description1: 'Exploration de nouvelles opportunités financières',
    description2: 'Investissements et partenariats pour le futur',
    type: 'Investissement',
    dateCreation: '2023-12-01',
    epargne: true,
    aide: true,
    groupeWhatsapp: 'https://chat.whatsapp.com/invitationLink3',
    idRejetes: ['m4'],
  },
];

export const membres: TMembre[] = [
  {
    id: 'm1',
    idReunion: 'r1',
    nom: 'Jean Dupont',
    email: 'jean.dupont@example.com',
    password: 'securePassword1',
    role: 'Président',
    metier: 'Ingénieur',
    commenceTravail: '2010-06-15',
    demandeAdhesion: true,
    approuvee: false,
    actif: true,
  },
  {
    id: 'm2',
    idReunion: 'r2',
    nom: 'Marie Curie',
    email: 'marie.curie@example.com',
    password: 'securePassword2',
    role: 'Trésorier',
    metier: 'Scientifique',
    commenceTravail: '2012-03-22',
    demandeAdhesion: true,
    approuvee: true,
    actif: true,
  },
  {
    id: 'm3',
    idReunion: 'r3',
    nom: 'Albert Einstein',
    email: 'albert.einstein@example.com',
    password: 'securePassword3',
    role: 'Censeur',
    metier: 'Physicien',
    commenceTravail: '2005-11-05',
    demandeAdhesion: false,
    approuvee: true,
    actif: false,
  },
  {
    id: 'm4',
    idReunion: 'r4',
    nom: 'Isaac Newton',
    email: 'isaac.newton@example.com',
    password: 'securePassword4',
    role: 'VicePrésident',
    metier: 'Mathématicien',
    commenceTravail: '2008-01-12',
    demandeAdhesion: true,
    approuvee: false,
    actif: true,
  },
  {
    id: 'm5',
    idReunion: 'r5',
    nom: 'Ada Lovelace',
    email: 'ada.lovelace@example.com',
    password: 'securePassword5',
    role: 'Secrétaire',
    metier: 'Programmeuse',
    commenceTravail: '2015-09-30',
    demandeAdhesion: true,
    approuvee: true,
    actif: true,
  },
  {
    id: 'm6',
    idReunion: 'r6',
    nom: 'Grace Hopper',
    email: 'grace.hopper@example.com',
    password: 'securePassword6',
    role: 'Membre',
    metier: 'Informaticienne',
    commenceTravail: '2018-05-25',
    demandeAdhesion: true,
    approuvee: true,
    actif: false,
  },
  {
    id: 'm7',
    idReunion: 'r7',
    nom: 'Nikola Tesla',
    email: 'nikola.tesla@example.com',
    password: 'securePassword7',
    role: 'Président',
    metier: 'Inventeur',
    commenceTravail: '2020-12-01',
    demandeAdhesion: false,
    approuvee: true,
    actif: true,
  },
  {
    id: 'm8',
    idReunion: 'r8',
    nom: 'Rosalind Franklin',
    email: 'rosalind.franklin@example.com',
    password: 'securePassword8',
    role: 'VicePrésident',
    metier: 'Biologiste',
    commenceTravail: '2017-07-14',
    demandeAdhesion: true,
    approuvee: false,
    actif: false,
  },
];


export const transactions: TTransaction[] = [
  {
    id: 't1',
    idReunion: 'r1',
    idReceveur: 'm1',
    type: 'Cotisation',
    status: 'Acceptée',
    montant: '500',
    dateTransaction: '2023-02-10',
    description: 'Cotisation mensuelle',
    tauxInteret: '',
    duree: '12',
    frequenceTransaction: 1,
    approuvee: true,
  },
  {
    id: 't2',
    idReunion: 'r2',
    idReceveur: 'm2',
    type: 'Prêt',
    status: 'En attente',
    montant: '1000',
    dateTransaction: '2023-03-05',
    description: 'Prêt pour projet personnel',
    tauxInteret: '5',
    duree: '6',
    frequenceTransaction: 0,
    approuvee: false,
  },
  {
    id: 't3',
    idReunion: 'r1',
    idReceveur: 'm3',
    type: 'Versement',
    status: 'Rejetée',
    montant: '300',
    dateTransaction: '2023-04-12',
    description: 'Versement de l investissement',
    tauxInteret: '',
    duree: '',
    frequenceTransaction: 0,
    approuvee: false,
  },
  {
    id: 't4',
    idReunion: 'r2',
    idReceveur: 'm4',
    type: 'Aide',
    status: 'Acceptée',
    montant: '200',
    dateTransaction: '2023-05-20',
    description: 'Aide pour urgence familiale',
    tauxInteret: '',
    duree: '',
    frequenceTransaction: 0,
    approuvee: true,
  },
];

export const activites: TActivite[] = [
  {
    id: 'a1',
    idReunion: 'r1',
    type: 'Événement',
    titre: 'Conférence annuelle',
    description: 'Conférence sur les nouvelles opportunités d’investissement',
    dateCreation: '2023-04-01',
    optionVote1: '',
    optionVote2: '',
    resultat: 'Aucun',
    lieu: 'Paris',
    heure: '10:00',
    idReceveur: '',
  },
  {
    id: 'a2',
    idReunion: 'r2',
    type: 'Vote',
    titre: 'Élection du trésorier',
    description: 'Élection pour le nouveau trésorier',
    dateCreation: '2023-05-10',
    optionVote1: 'Jean Dupont',
    optionVote2: 'Marie Curie',
    resultat: 'Option 1',
    lieu: '',
    heure: '',
    idReceveur: '',
  },
  {
    id: 'a3',
    idReunion: 'r1',
    type: 'Badge',
    titre: 'Badge de reconnaissance',
    description: 'Badge décerné pour contribution exceptionnelle',
    dateCreation: '2023-06-15',
    optionVote1: '',
    optionVote2: '',
    resultat: 'Aucun',
    lieu: '',
    heure: '',
    idReceveur: 'm3',
  },
];

export const notifications: TNotification[] = [
  {
    id: 'n1',
    idReunion: 'r1',
    idDestinateur: 'm1',
    titre: 'Rappel Cotisation',
    message: 'N’oubliez pas de payer votre cotisation mensuelle avant le 15.',
    lu: false,
    dateCreation: '2023-03-01',
    urlRedirection: 'https://example.com/payer-cotisation',
  },
  {
    id: 'n2',
    idReunion: 'r2',
    idDestinateur: 'm2',
    titre: 'Invitation à la réunion',
    message: 'Vous êtes invité à la réunion mensuelle le 25 mars.',
    lu: true,
    dateCreation: '2023-03-05',
    urlRedirection: 'https://example.com/reunion-mensuelle',
  },
];
